### ISSUE TITLE
Execute Chef Component task with non-zero exit code does not fail

### ISSUE THREAD

**Issue by gsreynolds** [chef-partners/azuredevops-chef-extension#12]
A failing Cookstyle, ChefSpec or Test Kitchen run returning a non-zero exit code does not fail the Execute Chef Component task.

With cookstyle offences, failing ChefSpecs and Test Kitchen runs that fail, the following will all pass as successful/green currently:
```yaml
    - task: chef-software.chef-preview.execute.component-preview@2
      displayName: 'Cookstyle'
      inputs:
        component: 'chef'
        arguments: 'exec cookstyle'
    - task: chef-software.chef-preview.execute.component-preview@2
      displayName: 'ChefSpec'
      inputs:
        component: 'chef'
        arguments: 'exec rspec'
    - task: chef-software.chef-preview.execute.component-preview@2
      displayName: Test Kitchen - test
      inputs:
        component: kitchen
        arguments: test
        envvars: |
          KITCHEN_YAML="kitchen.yml"
        workingdir: $(Build.SourcesDirectory)
```
