### ISSUE TITLE
Unable to run chef tasks with new Chef extension 

### ISSUE THREAD

**Issue by raghureddy45** [chef-partners/azuredevops-chef-extension#16]
Hello Team, 
After installing New Chef extension to ADO project. I am unable to run chef related tasks. Can someone share examples on how to use tasks to upload cookbook to chef server and chef supermarket.?

`Private BuildAgent OS: Redhat 7`
`Chef extension Version: 3.0.37`

Please see the errors encountered while running the chef tasks.

YAML Code
```
    - task: ChefKnife@1
      displayName: 'upload cookbook'
      inputs:
        component: 'knife'
        arguments: 'cookbook upload $(Build.Repository.Name)'
        workingdir: '$(Agent.WorkFolder)/cookbooks/$(Build.Repository.Name)'
```
Errot while running the Job
```
Starting: upload cookbook
==============================================================================
Task         : Chef Knife
Description  : Run scripts with Knife commands on your Chef workstation
Version      : 1.0.21
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/chef-knife
==============================================================================
##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
Finishing: upload cookbook
```

I have tried this as well. But the job is saying that no task found with that name. 

```
    - task: chef-software.chef-preview.execute.component-preview@2
      displayName: 'Cookstyle'
      inputs:
        component: 'chef'
        arguments: 'exec cookstyle'
```

```
A task is missing. The pipeline references a task called 'chef-software.chef-preview.execute.component-preview'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 2, job 'Build', step ''.)
```
